<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net9.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <RunAOTCompilation>true</RunAOTCompilation>
        <WasmStripILAfterAOT>true</WasmStripILAfterAOT>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser"/>
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Orange\Orange.csproj"/>
    </ItemGroup>
</Project>
