name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    # sets up .NET 8!
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish OrangePriceCalc.csproj -c Release -o release --nologo

    # changes the base-tag in index.html from '/' to 'This repo?' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to OrangePriceCalc
      run: sed -i 's/<base href="\/" \/>/<base href="\/OrangePriceCalc\/" \/>/g' release/wwwroot/index.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot